export const getMedicines = () => {
  const meds = [
    {
      ingredients: ["water", "iron", "sugar"],
      name: "medicineA",
      price: 200,
      description: "description",
      quantity: 280,
      sales: 50,
      picture: "https://rhc.nhsggc.org.uk/media/1331/medicines.png?width=262&height=187&mode=max",
      use: "Pain Relief",
    },
    {
      ingredients: [],
      name: "medicineB",
      price: 200,
      description: "description",
      quantity: 280,
      sales: 50,
      picture: "https://rhc.nhsggc.org.uk/media/1331/medicines.png?width=262&height=187&mode=max",
      use: "Infection Treatment",
    },
    {
      ingredients: [],
      name: "medicineC",
      price: 200,
      description: "description",
      quantity: 280,
      sales: 50,
      picture: "https://rhc.nhsggc.org.uk/media/1331/medicines.png?width=262&height=187&mode=max",
      use: "Cardiovascular Health",
    },
    {
      ingredients: [],
      name: "medicineD",
      price: 200,
      description: "description",
      quantity: 280,
      sales: 50,
      picture: "https://rhc.nhsggc.org.uk/media/1331/medicines.png?width=262&height=187&mode=max",
      use: "Cardiovascular Health",
    },
    {
      ingredients: [],
      name: "medicineE",
      price: 200,
      description: "description",
      quantity: 280,
      sales: 50,
      picture: "https://rhc.nhsggc.org.uk/media/1331/medicines.png?width=262&height=187&mode=max",
      use: "Mental Health",
    },
    {
      ingredients: [],
      name: "medicineF",
      price: 200,
      description: "description",
      quantity: 280,
      sales: 50,
      picture: "https://rhc.nhsggc.org.uk/media/1331/medicines.png?width=262&height=187&mode=max",
      use: "Pain Relief",
    },
  ];
  return meds;
};
